apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ServiceAccount_guestbook_default.yaml
- ConfigMap_guestbook_kube-root-ca.crt.yaml
- Deployment_guestbook_frontend.yaml
- Service_guestbook_redis-master.yaml
- Service_guestbook_redis-slave.yaml
- Secret_guestbook_default-token-8wm8v.yaml
- Deployment_guestbook_redis-slave.yaml
- Service_guestbook_frontend.yaml
- Deployment_guestbook_redis-master.yaml
