apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeU1ERXhOakU0TWpJeE5Wb1hEVE15TURFeE5URTRNakl4TlZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSjZMCjBJYTROdXkwUCtCcFJhaldaV25aUnExYXc0RDRQRmxsdmRGQ1lWSytJMG5ZMFpZSVlxMjhqTzRETjRNQjhmSGgKdk9ZQUJXRUxWN3U0aG1KTGoxLzRwalQ0WDY2VGFvRkxOVEhIL2dVUGFBLy8xcVVaYjhDekplbmMzeXBQZFBjUApHRVhkemczNE5aQlRvWUNrU0VKSlJFN1B2eGMxU1lOSnpEVWNWTUxPb2pXdE5SbXRJU0srTTdxVk9sNjdBTDdFClVqUE55ajlrZzZBNkdzMU5NQlZoQXBUNlU2OGJRVHBKb0ZYWEVkOUY4RmlQUXJiQzNzMHV6UHZyMjRDT2Z6ZGcKazAzRnlPK0VIbk5DTnY1VGM1NDhYaVh5WHZWNUpPNHh3T3BKOE5scWU5SEdtVjRsUGNFVmpIK29mYi8zM3ZJNwpSY3RwcEZiR0RZY2FHZFNXdURrQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJRRlJML0FzZkswRGMwaTN5WDB2UjNCc25DcWZUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFTU2VTSEQ2UQp6anl1dmNxQkFyR1VkWlRDM2dJWjk2aHZxbTdRRitISUt3dGxMak9JL2tWaHB4cE4vRHhlSDIzMVUwWGhVTVNKCnBESnR0cm5yVStEbmpVUnpueEV0Umk3NFQ2WWxsaFg1OWUrTXpYcVMrOUdTeTkyTmdkaWlRT3NjKzRxV3NNcXAKdURIOXl4NHoyYkxnR0hKNkE2d0NBa1JpM3pvQlN1RE5TRzl0bUhsTStoTGRhWU9zcWNvR2k3dEF5MVdGbENIQwp3RGRRZGFXWTNNSHc2VkRGWEVPV3Q2TGRsTVRSWWZkVWxhakh6MW0vVXhIdnBFejVXRnZUajFEZnJkSnI4ZXc3ClBOQkVEMzlneHRWWFR5dTlCYVAxYW5RcG5oOEVtakhFSUlFNzFRaFljRkNMcmxwVVA1MFRXNU5menkraVlrV0EKWlV2Ykp4OVUzS1JUSEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: Z3Vlc3Rib29r
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrUjFjSFZhTFZBMk1rcEJSRVJPVW1aSWFXWk5ORk0wWDJSeVYzUjZZVkU0VTE5dFVuRmxMVzVsWDJjaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpuZFdWemRHSnZiMnNpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxZM0psZEM1dVlXMWxJam9pWkdWbVlYVnNkQzEwYjJ0bGJpMDRkMjA0ZGlJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKa1pXWmhkV3gwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pTURsbE5qazVNRFl0TkRCbU5TMDBZMk14TFRrek9ERXROekUyTUdFd1pUWTVZVFJtSWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tZDFaWE4wWW05dmF6cGtaV1poZFd4MEluMC5raFhZU3ZuVEpUclo3RlU5VGpiWmpXMk5kVlRYUGFVaDVkWW1ma0FNLXc0dEloZnJLNHUyLU1UckhXVzMwWWZtcVdieG1Qc2hqVGZvRmEwWGpJUnRSb0dBeDRzTmNYTDY4bWhPRWZEUFBMX2pfT0xTam50bE80bnZLYjg2cXNLVVdSbGpwbEs2YjcxcDI1V1p4ZGd3a2dpUUFrRUVYcXYtd3J2TmZmWWhqZlZYUTRqVTVYdk56T05iSVZNS25tYlpBRUdxQkpEQjFldVEzRjNiOWZ4SzMtRUVOOUNqQWJvdlFQQnhpWXRTN3VHUlhaY2p2VEp5amF0Q1lreWhWR3hKOGVzMTVfSy01WFdydGtJb0lXTWpXTnc3emJpQjJTVHUwRVgtVGdUcGYxWkFWU1R5OXJHMlZDZWxWRVRIVE5vU25mYy1NYWtzRUxFeGJhOTJRdGFDNWc=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 09e69906-40f5-4cc1-9381-7160a0e69a4f
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-01-31T16:25:06Z"
  name: default-token-8wm8v
  namespace: guestbook
type: kubernetes.io/service-account-token
